/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

//import com.raven.swing.MyTextField;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import login.swing.Button;
import login.swing.MyPasswordField;
import login.swing.MyTextField;
import model.UserModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author programmer
 */
public class PanelLogin extends javax.swing.JLayeredPane {

    /**
     * Creates new form PanelLogin
     */
    
    private UserModel user;

    public UserModel getUser() {
        return user;
    }
    
    public PanelLogin(ActionListener eventLogin) {
        initComponents();
        initLogin(eventLogin);
        panelLogin.setVisible(true);
    }

    private void initLogin(ActionListener eventLogin) {
        panelLogin.setLayout(new MigLayout("wrap", "push[center]push", "push[]25[]25[]35[]push"));
        JLabel label = new JLabel();
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/useri.png"))); // NOI18N
        panelLogin.add(label);
        MyTextField username = new MyTextField();
        username.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/user.png")));
        username.setHint("NOM D' UTILISATEUR");
        panelLogin.add(username, "w 60%");
        MyPasswordField password = new MyPasswordField();
        password.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icon/pass.png")));
        password.setHint("MOT DE PASSE");
        panelLogin.add(password, "w 60%");
        Button connexion = new Button();
        connexion.setBackground(new Color(0,46,245));
        connexion.setForeground(new Color(250,250,250));
        connexion.addActionListener(eventLogin);
        connexion.addActionListener(new ActionListener(){
             @Override
            public void actionPerformed(ActionEvent ae){
                String usern = username.getText().trim();
                String passw =  String.valueOf( password.getPassword());
                user = new UserModel(usern,passw);
            }
        });
        connexion.setText("CONNEXION");
        panelLogin.add(connexion,"w 40%, h 40");
        

//        label.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
//        label.setForeground(new java.awt.Color(51, 102, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setName(""); // NOI18N

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(panelLogin, "card2");
    }// </editor-fold>//GEN-END:initComponents
//    @Override
//    protected void paintComponent(Graphics graphs){
//        Graphics2D g1 = (Graphics2D)graphs;
//        GradientPaint pa = new GradientPaint(0,0,new Color(0, 118, 245),0,getHeight(),new Color(0, 41, 245));
//        g1.setPaint(pa);
//        g1.fillRect(0, 0, getWidth(), getHeight());
//        super.paintComponent(graphs);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables
}
